// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using EasySheba.Data;

namespace EasySheba.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326180000_MakeBedFieldsNullable")]
    partial class MakeBedFieldsNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // snapshot not required for this manual migration file
        }
    }
}
